server:
  port: 8080
logging:
  level:
    hu.eteosf.organization.demo:
      service.CustomerServiceImpl: debug
spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:asd